# Generated by Django 3.1.3 on 2020-11-25 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytube', '0002_auto_20201126_0321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='id',
            new_name='commentid',
        ),
    ]
