# Generated by Django 3.1.3 on 2020-11-22 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytube', '0002_auto_20201123_0510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='token',
        ),
    ]
